- hosts: localhost
  roles:
    - role: elliotweiser.osx-command-line-tools
  vars_files:
    - ./defaults.yaml
  vars:
    go_root: "/usr/local/go"
    go_path: "{{ ansible_env.HOME }}/go"
    fabric_version: "latest"
    fabric_config_dir: "{{ ansible_env.HOME }}/.config/fabric"
  pre_tasks:
    - import_tasks: ansible/tasks/validation.yaml
      tags:
        - always
    
    - name: Update Brew
      community.general.homebrew:
        update_homebrew: yes
      tags:
        - install
        - core
      when: not (ansible_check_mode | default(false))

  tasks:
    - import_tasks: ansible/tasks/git-setup.yaml
    - import_tasks: ansible/tasks/cli-tools.yaml
    - import_tasks: ansible/tasks/gui-tools.yaml
    - import_tasks: ansible/tasks/davinci-resolve.yaml
    - import_tasks: ansible/tasks/app-store-apps.yaml
    - import_tasks: ansible/tasks/zsh.yaml
    - import_tasks: ansible/tasks/fonts.yaml
    - import_tasks: ansible/tasks/themes.yaml
    - import_tasks: ansible/tasks/osx.yaml
    - import_tasks: ansible/tasks/iterm.yaml
    - import_tasks: ansible/tasks/nvim.yaml
    - import_tasks: ansible/tasks/security.yaml
    - import_tasks: ansible/tasks/dotfiles.yaml
    - import_tasks: ansible/tasks/node.yaml
    - import_tasks: ansible/tasks/rust.yaml
    - import_tasks: ansible/tasks/remove-unwanted-packages.yaml
    - import_tasks: ansible/tasks/dock.yaml
    - import_tasks: ansible/tasks/ai-tools.yaml
