- hosts: localhost

  vars:
    source_ssh_key: "./.ssh/id_rsa"
    dest_ssh_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    go_root: "/usr/local/go"
    go_path: "{{ ansible_env.HOME }}/go"
    fabric_version: "latest"
    fabric_config_dir: "{{ ansible_env.HOME }}/.config/fabric"
  vars_files:
    - ./vars/api_keys.yml
  tasks:
    - name: Ensure .ssh directory exists
      file:
        path: "{{ lookup('env', 'HOME') }}/.ssh"
        state: directory
        mode: "0700"
      ignore_errors: no

    - import_tasks: ansible/tasks/ssh.yaml

    - name: Set correct permissions for SSH key
      file:
        path: "{{ dest_ssh_key }}"
        mode: "0600"
      when: dest_ssh_key is file
      ignore_errors: no

    - name: Verify SSH key installation
      stat:
        path: "{{ dest_ssh_key }}"
      register: ssh_check
      failed_when: not ssh_check.stat.exists

    - name: Ensure ~/.config/fabric directory exists
      ansible.builtin.file:
        path: "{{ fabric_config_dir }}"
        state: directory
        mode: "0755"

    - name: Copy Fabric AI .env file
      ansible.builtin.template:
        src: "./ansible/templates/fabric/.env"
        dest: "{{ fabric_config_dir }}/.env"
        mode: "0600"

    - name: Copy Fabric settings.yaml file
      ansible.builtin.template:
        src: "./ansible/templates/fabric/settings.yaml"
        dest: "{{ fabric_config_dir }}/settings.yaml"
        mode: "0600"
