---
- hosts: localhost
  vars_files:
    - ./defaults.yaml
  vars:
    homebrew_environment: "{{ {'SUDO_ASKPASS': lookup('env', 'SUDO_ASKPASS')} if lookup('env', 'SUDO_ASKPASS') else {} }}"
  tasks:
    - import_tasks: ansible/tasks/update.yaml
      tags:
        - update
