# ===================================
# PKM
# ===================================

- name: Install Drafts
  ignore_errors: yes
  tags:
    - app-store
  community.general.mas:
    id: 1435957248
    state: latest

- name: Install Kindle
  ignore_errors: yes
  tags:
    - app-store
  community.general.mas:
    id: 405399194
    state: latest

- name: Install Things
  ignore_errors: yes
  tags:
    - app-store
  community.general.mas:
    id: 904280696
    state: latest

- name: Install Belongings
  ignore_errors: yes
  tags:
    - app-store
  community.general.mas:
    id: 1580380407
    state: latest

# ===================================
# iWork Suite
# ===================================

- name: Install Keynote
  ignore_errors: yes
  tags:
    - app-store
  community.general.mas:
    id: 409183694
    state: latest

- name: Install Numbers
  ignore_errors: yes
  tags:
    - app-store
  community.general.mas:
    id: 409203825
    state: latest

- name: Install Pages
  ignore_errors: yes
  tags:
    - app-store
  community.general.mas:
    id: 409201541
    state: latest

# ===================================
# Creativity Suite
# ===================================

- name: Install GarageBand
  ignore_errors: yes
  tags:
    - app-store
  community.general.mas:
    id: 682658836
    state: latest

# ===================================
# App Development
# ===================================

- name: Install XCode
  ignore_errors: yes
  tags:
    - app-store
  community.general.mas:
    id: 497799835
    state: latest

- name: Install TestFlight
  ignore_errors: yes
  tags:
    - app-store
  community.general.mas:
    id: 899247664
    state: latest

- name: Install RocketSim
  ignore_errors: yes
  tags:
    - app-store
  community.general.mas:
    id: 1504940162
    state: latest

- name: Install Developer
  ignore_errors: yes
  tags:
    - app-store
  community.general.mas:
    id: 640199958
    state: latest

- name: Install Swift Playground
  ignore_errors: yes
  tags:
    - app-store
  community.general.mas:
    id: 1496833156
    state: latest

- name: Install Frame Array
  ignore_errors: yes
  tags:
    - app-store
  community.general.mas:
    id: 6744052024
    state: latest

- name: Install Framous
  ignore_errors: yes
  tags:
    - app-store
  community.general.mas:
    id: 6636520519
    state: latest

- name: Install Helm
  ignore_errors: yes
  tags:
    - app-store
  community.general.mas:
    id: 6479357934
    state: latest

- name: Install Picasso
  ignore_errors: yes
  tags:
    - app-store
  community.general.mas:
    id: 6472062986
    state: latest

# ===================================
# Design
# ===================================

- name: Install DarkRoom
  ignore_errors: yes
  tags:
    - app-store
  community.general.mas:
    id: 953286746
    state: latest

- name: Install Affinity Designer 2
  ignore_errors: yes
  tags:
    - app-store
  community.general.mas:
    id: 1616831348
    state: latest

- name: Install Affinity Photo 2
  ignore_errors: yes
  tags:
    - app-store
  community.general.mas:
    id: 1616822987
    state: latest

# ===================================
# Utilities
# ===================================

- name: Install Yoink
  ignore_errors: yes
  tags:
    - app-store
  community.general.mas:
    id: 457622435
    state: latest

- name: Install Dark Noise
  ignore_errors: yes
  tags:
    - app-store
  community.general.mas:
    id: 1465439395
    state: latest

- name: Install Amphetamine
  ignore_errors: yes
  tags:
    - app-store
  community.general.mas:
    id: 937984704
    state: latest

- name: Install RCMD
  ignore_errors: yes
  tags:
    - app-store
  community.general.mas:
    id: 1596283165
    state: latest

- name: Install PopClip
  ignore_errors: yes
  tags:
    - app-store
  community.general.mas:
    id: 445189367
    state: latest

- name: Install DaisyDisk
  ignore_errors: yes
  tags:
    - app-store
  community.general.mas:
    id: 411643860
    state: latest

- name: Install The Unarchiver
  ignore_errors: yes
  tags:
    - app-store
  community.general.mas:
    id: 425424353
    state: latest

- name: Install Speedtest
  ignore_errors: yes
  tags:
    - app-store
  community.general.mas:
    id: 1153157709
    state: latest

- name: Install Just Press Record
  ignore_errors: yes
  tags:
    - app-store
  community.general.mas:
    id: 1033342465
    state: latest

- name: Install Spokenly
  ignore_errors: yes
  tags:
    - app-store
  community.general.mas:
    id: 6740315592
    state: latest

- name: Install Auth for Tesla
  ignore_errors: yes
  tags:
    - app-store
  community.general.mas:
    id: 1552058613
    state: latest

# ===================================
# Safari Extensions
# ===================================

- name: Install 1Password for Safari
  ignore_errors: yes
  tags:
    - app-store
  community.general.mas:
    id: 1569813296
    state: latest

- name: Install 1Blocker
  ignore_errors: yes
  tags:
    - app-store
  community.general.mas:
    id: 1365531024
    state: latest

- name: Install Wipr
  ignore_errors: yes
  tags:
    - app-store
  community.general.mas:
    id: 1662217862
    state: latest

- name: Install Stop The Madness
  ignore_errors: yes
  tags:
    - app-store
  community.general.mas:
    id: 6471380298
    state: latest

- name: Install Baking Soda
  ignore_errors: yes
  tags:
    - app-store
  community.general.mas:
    id: 1601151613
    state: latest

- name: Install Vinegar
  ignore_errors: yes
  tags:
    - app-store
  community.general.mas:
    id: 1591303229
    state: latest

- name: Install Sink It For Reddit
  ignore_errors: yes
  tags:
    - app-store
  community.general.mas:
    id: 6449873635
    state: latest

- name: Install Consent-O-Matic
  ignore_errors: yes
  tags:
    - app-store
  community.general.mas:
    id: 1606897889
    state: latest

- name: Install Hush
  ignore_errors: yes
  tags:
    - app-store
  community.general.mas:
    id: 1544743900
    state: latest
