- name: Install apps from App Store
  ansible.builtin.command: brew bundle install --file "{{ playbook_dir }}/Brewfile.app-store"
  environment: "{{ homebrew_environment }}"
  register: brew_bundle_app_store
  changed_when: >-
    'Installing' in brew_bundle_app_store.stdout or
    'Upgrading' in brew_bundle_app_store.stdout or
    'Tapping' in brew_bundle_app_store.stdout
  ignore_errors: true
  tags:
    - app-store
    - install
