- name: Install CLI packages
  community.general.homebrew:
    name: "{{ item }}"
    state: latest
  ignore_errors: yes
  with_items:
    - zellij
    - fzf
    - z
    - gh
    - aria2
    - curl
    - claude
    - wget
    - yarn
    - pnpm
    - tree
    - thefuck
    - mas
    - starship
    - httpie
    - jq
    - lazygit
    - glances
    - tldr
    - fd
    - asciinema
    - eza
    - bat
    - robotsandpencils/made/xcodes
    - rust
    - hammerspoon
    - deno
    - terraform
    - xcode-build-server
    - xcbeautify
    - swiftformat
    # Apples
    - swift-format
  tags:
    - install
    - productivity
    - cli

- name: Better fzf shell integration
  ansible.builtin.shell: $(brew --prefix)/opt/fzf/install
  tags:
    - install
    - productivity
    - cli
