- name: Install fonts from Brewfile
  ansible.builtin.command: brew bundle --force --file "{{ playbook_dir }}/Brewfile.fonts"
  environment: "{{ homebrew_environment }}"
  register: brew_bundle_fonts
  changed_when: >-
    'Installing' in brew_bundle_fonts.stdout or
    'Upgrading' in brew_bundle_fonts.stdout
  ignore_errors: true
  tags:
    - install
    - fonts
