- name: Setup finder settings
  shell: "{{ item }}"
  with_items:
    # Show Path bar in Finder
    - defaults write com.apple.finder ShowPathbar -bool true
    # Show Status bar in Finder
    - defaults write com.apple.finder ShowStatusBar -bool true

    # Show icons for hard drives, servers, and removable media on the desktop
    - defaults write com.apple.finder ShowExternalHardDrivesOnDesktop -bool true
    - defaults write com.apple.finder ShowHardDrivesOnDesktop -bool true
    - defaults write com.apple.finder ShowMountedServersOnDesktop -bool true
    - defaults write com.apple.finder ShowRemovableMediaOnDesktop -bool true

    # Show absolute path in finder's title bar.
    - defaults write com.apple.finder _FXShowPosixPathInTitle -bool YES

    # Show the ~/Library folder
    - chflags nohidden ~/Library

    # Set default Finder location to home folder (~/)
    - defaults write com.apple.finder NewWindowTarget -string "PfLo"
    - defaults write com.apple.finder NewWindowTargetPath -string "file://${HOME}"

    # Use list view in all Finder windows by default
    # Four-letter codes for the other view modes: `icnv`, `clmv`, `Flwv`
    - defaults write com.apple.finder FXPreferredViewStyle -string "Nlsv"

    # Use current directory as default search scope in Finder
    - defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"

    # show all filename extensions
    - defaults write NSGlobalDomain AppleShowAllExtensions -bool true

    # Disable ext change warning
    - defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

    # Set a blazingly fast keyboard repeat rate
    - defaults write NSGlobalDomain KeyRepeat -int 0

    # Finder: empty Trash securely by default
    - defaults write com.apple.finder EmptyTrashSecurely -bool true

    # Panels
    # ----------------------------------------------------------------------

    # Panels: disable the “Are you sure you want to open this application?” dialog
    - defaults write com.apple.LaunchServices LSQuarantine -bool false

    # Panels: enable full keyboard access for all controls (e.g. enable Tab in modal dialogs)
    - defaults write NSGlobalDomain AppleKeyboardUIMode -int 3

    # Misc
    # ----------------------------------------------------------------------

    # Misc: disable Dictionary results
    - defaults write com.apple.spotlight DictionaryLookupEnabled -bool false

    # Misc: disable auto-correct
    - defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false

    # Notifications Center
    # ----------------------------------------------------------------------
    # Extend the banner time to 20 seconds
    - defaults write com.apple.notificationcenterui bannerTime 20

  tags:
    - install
    - osx

- name: Configure terminal to open in same directory by default
  shell: defaults write com.apple.Terminal NewTabWorkingDirectoryBehavior -bool true
  tags:
    - install
    - osx

- name: Show hidden files in finder
  osx_defaults:
    domain: com.apple.Finder
    key: AppleShowAllFiles
    type: bool
    value: true
    state: present
  tags:
    - install
    - osx

- name: Set automatic software updates to true
  osx_defaults:
    domain: /Library/Preferences/com.apple.SoftwareUpdate
    key: AutomaticCheckEnabled
    type: int
    value: 1
  become: yes
  tags:
    - install
    - osx

- name: Restart finder
  changed_when: true
  command: killall Finder
  tags:
    - install
    - osx
