- name: Ensure SSH directory exists
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.ssh"
    state: directory
    mode: "0700"
  tags:
    - install
    - ssh
    - security

- name: Use 1Password SSH Agent
  ansible.builtin.template:
    src: ../templates/ssh_config.j2
    dest: ~/.ssh/config
    mode: "0600"
  tags:
    - install
    - ssh
    - security
- name: Install personal public SSH Key
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/.ssh/{{ personal_public_ssh_key }}"
    dest: "{{ lookup('env', 'HOME') }}/.ssh/{{ personal_public_ssh_key }}"
    mode: "0644"
  tags:
    - install
    - ssh
    - security
- name: Install work public SSH Key
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/.ssh/{{ work_public_ssh_key }}"
    dest: "{{ lookup('env', 'HOME') }}/.ssh/{{ work_public_ssh_key }}"
    mode: "0644"
  tags:
    - install
    - ssh
    - security
